services:
  - type: web
    name: taskmanager-backend
    env: python
    buildCommand: pip install --upgrade pip==25.0.1 && pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
